### ISSUE TITLE
Auth (Pinia) doesn't seem to work anymore?

### ISSUE THREAD

**Issue by Loosie94** [bryantgillespie/nuxt3-directus-starter#13]
Hi Bryant,

When trying to launch locally I get the error: `[🍍]: getActivePinia was called with no active Pinia. Did you forget to install pinia? const pinia = createPinia() app.use(pinia) This will fail in production.`

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/13577640/202544586-4297f7f9-d845-4057-99e0-7a5b2c9e6e1f.png">

I did not have this issue before, and have Pinia installed. Any idea how to fix this?
Thanks!

**Comment by bryantgillespie** [comment]
It's a Nuxt config issue. Looks like another breaking change.

https://nuxt.com/docs/migration/configuration#migration-1
<img width="852" alt="ScreenShot 2022-11-17 at 15 08 36@2x" src="https://user-images.githubusercontent.com/23302570/202548827-546a6d21-bd1d-4d2a-a834-2ca5776f2691.png">

**Comment by Loosie94** [comment]
Thanks, that helped already!
It had to do with: 'floating-vue/nuxt' in my buildModules. I renamed this to `modules`, removed this one and renamed `useMeta` to `useHead`.

That seems to did the trick, but I only do not get styling anymore. Any idea what that can be?

Screenshot:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13577640/202553187-8e66e802-5a7d-4162-8ff2-74f9da7974b9.png">

**Comment by bryantgillespie** [comment]
Check out the changes on this commit
https://github.com/bryantgillespie/nuxt3-directus-starter/commit/ed1857c5d831e8533580d455ecff13a931061427

It likely has to do with the changes they made to Nuxt Config recently
