### ISSUE TITLE
getFriendlyDate Always returns "th" as date suffix

### ISSUE THREAD

**Issue by dnndev** [bryantgillespie/nuxt3-directus-starter#14]
When passing a date to getFriendlyDate() in /utils/time.js  the function always returns a "th" for the suffix. For example, passing in `2022-12-02T22:38:48.632Z` it returns `Fri, December 2th, 2022`. I believe the issue is on line #86. The `date` constant is not passed into the `dateSuffix` function. The corrected version should look like:

```
const formatted = `${dayName}, ${monthName} ${date}${dateSuffix(date)}, ${year}`
```

**Comment by bryantgillespie** [comment]
Good catch @dnndev 👍 . Fixed with https://github.com/bryantgillespie/nuxt3-directus-starter/commit/eab605dfe17e6a7cb9da16430e5f5574987dd619
