### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dnndev** [bryantgillespie/nuxt3-directus-starter#15]
I'm using an unmodified version of the starter project, with the exception of the info for my Directus DB (Directus Cloud).

This error occurs after:
1) I have logged in on the home page
2) The page has been sitting idle for 15+ minutes (the session timeout or auth expiration)
3) I refresh the page

Errors are logged to the terminal. 

```
✔ Nitro built in 239 ms                                                            nitro 10:29:43
Token found, fetching user from server                                                   10:45:19
Exception in PromiseRejectCallback:
@directus/sdk:848
    }
    ^

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
@directus/sdk:954
                    await this._auth.refreshIfExpired();
                                     ^

RangeError: Maximum call stack size exceeded
TransportError: Maximum call stack size exceeded                                         10:45:19
    at Transport.request (@directus/sdk:729:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Transport.get (@directus/sdk:733:16)
    at async MeHandler.read (@directus/sdk:455:26)
    at async /Users/kford/dev/nuxt3-directus-starter/plugins/directus.ts:67:19
    at async Object.callAsync (file:///Users/kford/dev/nuxt3-directus-starter/node_modules/unctx/dist/index.mjs:53:16)
    at async applyPlugin (/Users/kford/dev/nuxt3-directus-starter/node_modules/nuxt/dist/app/nuxt.mjs:97:23)
    at async Module.applyPlugins (/Users/kford/dev/nuxt3-directus-starter/node_modules/nuxt/dist/app/nuxt.mjs:107:5)
    at async createNuxtAppServer (/Users/kford/dev/nuxt3-directus-starter/node_modules/nuxt/dist/app/entry.mjs:29:7)
    at async default (file:///Users/kford/dev/nuxt3-directus-starter/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18) {
  parent: TransportError: Maximum call stack size exceeded
      at Transport.request (@directus/sdk:729:19)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Transport.post (@directus/sdk:748:16)
      at async refreshPromise (@directus/sdk:854:30)
      at async Auth.refreshIfExpired (@directus/sdk:843:13)
      at async Transport.beforeRequest (@directus/sdk:954:21)
      at async Transport.request (@directus/sdk:697:22)
      at async Transport.get (@directus/sdk:733:16)
      at async MeHandler.read (@directus/sdk:455:26)
      at async /Users/kford/dev/nuxt3-directus-starter/plugins/directus.ts:67:19 {
    parent: TransportError: Maximum call stack size exceeded
        at Transport.request (@directus/sdk:729:19)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Transport.post (@directus/sdk:748:16)
        at async refreshPromise (@directus/sdk:854:30)
        at async Auth.refreshIfExpired (@directus/sdk:843:13)
        at async Transport.beforeRequest (@directus/sdk:954:21)
        at async Transport.request (@directus/sdk:697:22)
        at async Transport.post (@directus/sdk:748:16)
        at async refreshPromise (@directus/sdk:854:30)
        at async Auth.refreshIfExpired (@directus/sdk:843:13) {
      parent: [TransportError],
      response: undefined,
      errors: []
    },
    response: undefined,
    errors: []
  },
  response: undefined,
  errors: []
}
```

This happens on both Chrome and Firefox (for Mac). I have not tested it on Safari or Windows. The user information is still  displayed in the login form component and the user appears logged in. At the same time, I get a number of Hydration mismatch errors in the browser console from components linked to authorization like this one:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/1757808/208314385-e23b67ac-d7e4-462c-8fff-f2a78f260f0e.png">

If it is useful, here's a look at the cookies:

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/1757808/208314521-9e3f2b5f-df0b-4ab2-b7c2-b9a4c2fab69f.png">

**Comment by dnndev** [comment]
I don't know if this is related to the secure cookies note in the Directus SDK docs or not.  As per the note, I did run this on Firefox and, as you can see in the screenshot, the cookies are not secure.

<img width="754" alt="image" src="https://user-images.githubusercontent.com/1757808/208314845-ab4288c6-cfad-49c4-81e5-5505a4d3dcec.png">

**Comment by bryantgillespie** [comment]
Thanks for adding the issue here @dnndev .
I'm aware of it but I was hoping I had fixed it with one of the latest updates. Apparently I did not.

The issue is a combination of the SSR within Nuxt and the Directus SDK not playing nice together when you are logged in.

Here was a past resolution on it.
https://github.com/directus/sdk/issues/53#issuecomment-1245152033

At some point, the Nuxt composable `useCookie()` stopped working the same way it was and hence the reason why I added `universal-cookie` to the Directus plugin. But I must have messed up the implementation somewhere.
https://github.com/bryantgillespie/nuxt3-directus-starter/blob/main/plugins/directus.ts

I'll see if I can hack on it sometime this week to come up with a fix.

In the apps I've built with this starter, I usually turn SSR off for any authenticated 'app' pages because it's not really needed.

``` typescript
---
nuxt.config.ts
---
export default defineNuxtConfig({
  routeRules: {
    '/app/**': { ssr: false },
    '/signin/**': { ssr: false },
  },

  //   ...rest of config
)}

```

**Comment by bryantgillespie** [comment]
I think this should be sorted out now.
https://github.com/bryantgillespie/nuxt3-directus-starter/commit/910aad7b29fe93bfa447dae2633c89d26b36069c

Though I keep getting a couple hydration errors because it's not updating the store when the SDK retries the fetchUser call after refreshing the expired token. 

I was trying to avoid adding the refresh logic to the plugin because the SDK handles auto refresh for you. But I may end up having to do that.

**Comment by dnndev** [comment]
Thanks for getting to this so quickly @bryantgillespie. I have tested it and I'm no longer receiving the Max call stack size exceeded error. Thus far I haven't received any hydration errors either. I do see an error in the terminal but I'm guessing that's just a logged error from the expired token. I don't know if that's being logged from the SDK or elsewhere. When reloading the home page it does seem very slow, the user fetch is blocking loading of the rest of the page. This slowness is probably due to Directus Cloud Community being the backend. However, I wouldn't have thought it would be a blocking issue. Of course that is a different issue. I'll do more testing but think you can close this issue. Thanks again for your fast response!

**Comment by bryantgillespie** [comment]
@dnndev is the page slow to load every single time from a refresh? Or just whenever the token is expired?

**Comment by dnndev** [comment]
It was after it expired .. and then a few more loads beyond that. I'm pretty sure the issue is the slow response of the community version of Directus Cloud. Eventually the speed came back.  The main point, to me, was that when there was that delay, the first part of the page loaded fine -- up until the Auth portion. No other components or content was displayed. Once the user was finally loaded, the rest of the page finished displaying.  I had assumed it would be threaded and not block the rest of the page from loading under those conditions.

**Comment by bryantgillespie** [comment]
> Thus far I haven't received any hydration errors either. I do see an error in the terminal but I'm guessing that's just a logged error from the expired token. I don't know if that's being logged from the SDK or elsewhere.

That error is being logged from here if you want to remove it.

https://github.com/bryantgillespie/nuxt3-directus-starter/blob/910aad7b29fe93bfa447dae2633c89d26b36069c/store/auth.ts#L70-L83


> It was after it expired .. and then a few more loads beyond that. I'm pretty sure the issue is the slow response of the community version of Directus Cloud. Eventually the speed came back. The main point, to me, was that when there was that delay, the first part of the page loaded fine -- up until the Auth portion. No other components or content was displayed. Once the user was finally loaded, the rest of the page finished displaying. I had assumed it would be threaded and not block the rest of the page from loading under those conditions

I'll try to see if I recreate this and if there's something else going on. I was testing with a local copy of Directus, but the speed on Community Cloud has always been good for me even though it's free.

**Comment by dnndev** [comment]
Thanks for all your help with this. 

FYI, I am getting those hydration errors you mentioned after a session timeout and page reload.
