### ISSUE TITLE
Will this package be upgraded to new Nuxt Versions?

### ISSUE THREAD

**Issue by NatsuDragneelKl** [bryantgillespie/nuxt3-directus-starter#18]
Are there any plans for new Nuxt Releases?

**Comment by bryantgillespie** [comment]
Sure - been slacking on updating but this is fairly easy to upgrade manually too.

**See** https://github.com/bryantgillespie/nuxt3-directus-starter/commit/0008aad35f6ca0152fcdb2e88e5109f4989ed446
