### ISSUE TITLE
Good, but might need an update?

### ISSUE THREAD

**Issue by Loosie94** [bryantgillespie/nuxt3-directus-starter#2]
Hi,

I think your project is really looking good and see it as the perfect starter for my next project, but the repo might need an update?
Because at the moment I'm facing some errors. For example the following one: 

`Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.vite/deps/ufo.js?v=107dadee' does not provide an export named 'isEqual' (at router.mjs:8:23)`

Any idea what is causing this?
Keep up the good work!

**Comment by bryantgillespie** [comment]
Definitely in need of an update! Thanks for the nudge @Loosie94.

I'll try to get a fix pushed in the next couple days. But my first guess is probably because I'm a bit bit behind on the Nuxt RC versions.

**Comment by Loosie94** [comment]
I updated all packages locally and is working better now. Thanks again!

**Comment by bryantgillespie** [comment]
@Loosie94 I've push a round of updates
https://github.com/bryantgillespie/nuxt3-directus-starter/commit/f5b09755e6ef50cd706b1d0ad146036f61f27ab8
