### ISSUE TITLE
Running Build in a fresh cloned repo gets the error 500

### ISSUE THREAD

**Issue by parich15** [bryantgillespie/nuxt3-directus-starter#20]
Cloned the repo and ran npx nuxi build. Generates for production, when accessed, it gives the next error:

![image](https://github.com/bryantgillespie/nuxt3-directus-starter/assets/60244188/b0e5d2ff-df63-4009-adcb-77f328c57392)
![image](https://github.com/bryantgillespie/nuxt3-directus-starter/assets/60244188/1fdc99cf-3488-491e-9023-85c4ac97b583)

Im using this template for building a real production app (because Nuxt 3 is officialy out) and found this error when trying to preview. Before touching anything on my project I wanted to be sure that this error is not from my code, so I reclonated a fresh new repo and ran the build command only to found that gives me the same error. 
What could it be?

**Comment by parich15** [comment]
I commented the transpile and vite options and then it runs without problems.

**Comment by bryantgillespie** [comment]
Thanks for the notes. I'll get this updated 👍

**Comment by bryantgillespie** [comment]
incorporated in the latest update 👍
