### ISSUE TITLE
Demo Problems

### ISSUE THREAD

**Issue by M-GRV** [bryantgillespie/nuxt3-directus-starter#22]
The demo currently has an issue with the demo AUTH account. 

Also when grabbing pages the page images are broken.

Thanks!

**Comment by BlackDahlia313** [comment]
Looks like it might just be the way the directus demo is setup. Works fine on a pull

**Comment by M-GRV** [comment]
> Looks like it might just be the way the directus demo is setup. Works fine on a pull

this is true. Demo still has problems, but looks to be the demo directus instance.

**Comment by bryantgillespie** [comment]
Yes good catch. I messed up the Directus instance the demo is actually pointing to.
