### ISSUE TITLE
Your Start with local Directus "cors" error

### ISSUE THREAD

**Issue by NatsuDragneelKl** [bryantgillespie/nuxt3-directus-starter#3]
Hey, your project looks very cool!

But I run into problems regarding CORS and Directus

Have you any tipps to avoid this?

**Comment by bryantgillespie** [comment]
@NatsuDragneelKl Are you using Directus Cloud or a local instance?

If you're running locally a local, self-hosted Directus instance the as well and running into CORS issues, try setting these values in your Directus .env file to true.
```
CORS_ENABLED=true
CORS_ORIGIN=true
```
Here's the their docs on config.
https://docs.directus.io/self-hosted/config-options.html#cors
<img width="773" alt="ScreenShot 2022-08-12 at 11 23 20@2x" src="https://user-images.githubusercontent.com/23302570/184387432-b6f0297b-e61e-46a7-bf9d-aab0cdae2e1d.png">

**Comment by NatsuDragneelKl** [comment]
Hey, this seems related to Firefox (Build version is running) 

I try it with chrome and it seems to work there ;) thanks great package!
