### ISSUE TITLE
Hotreload with Tailwind classes

### ISSUE THREAD

**Issue by NatsuDragneelKl** [bryantgillespie/nuxt3-directus-starter#4]
I test some modules with tailwind and run into a problem.

In some cases new tailwind classes (which I never used before in template) applied on template (style doesnt work) with live reload.

I have to resave tailwind.config.js  so the page reload, after that my style was applied.

For example:

I never used the pt-32 class -> pt-32 wasn't applied

after resave tailwind.config.js the page reload and the style for pt-32 was applied.

Any Idea to resolve this? :(

**Comment by bryantgillespie** [comment]
Check out this commit.

https://github.com/bryantgillespie/nuxt3-directus-starter/commit/d34198c0517e84386905cd802dab9072fcae9b43

It looks I didn't have the `tailwind.config.js` file setup correctly.

**Comment by NatsuDragneelKl** [comment]
Yesterday evening, I checked the tailwind documentation as well and made this changes by myself.
I wanted to test the configuration for some time before I wanted to propose the changes to you

I can confirm that this changes solve the issue.

Thanks ;)
