### ISSUE TITLE
Scrollposition the same as previous page (slug pages)

### ISSUE THREAD

**Issue by NatsuDragneelKl** [bryantgillespie/nuxt3-directus-starter#5]
Hey, 

I run into a problem after experiment with the slug page stuff.

My slug pages are a longer as the basic examples here.

After clicking on links (within index) the slug page load, but the scroll position are the same as on the index. 

Any idea how I can fix this?

Cheers

**Comment by bryantgillespie** [comment]
I pushed a fix for this with latest commit. I don't think Nuxt has the scrollToTop property configured yet.

1. Add a plugin to /plugins directory
https://github.com/bryantgillespie/nuxt3-directus-starter/blob/fcf484c833c6d50ceb60d71b13c0fda20092d3b5/plugins/scroll.ts

2. Remove the script tag from default layout
https://github.com/bryantgillespie/nuxt3-directus-starter/blob/fcf484c833c6d50ceb60d71b13c0fda20092d3b5/layouts/default.vue

**Comment by NatsuDragneelKl** [comment]
Implemented this fix and adjust it for the "back to overview" function (history) for my individual purpose.

Thanks ;)
