### ISSUE TITLE
Readme followed, but Nuxt app not working?

### ISSUE THREAD

**Issue by Loosie94** [bryantgillespie/nuxt3-directus-starter#8]
Hi @bryantgillespie,

I've followed the exact steps you have specified in the readme.
First I had a local manual install of Directus, and then I tried the Directus Cloud install, but both don't seem to work.
The Nuxt install is working, but is not fetching any pages or users. Am I missing something?
I really like your setup, so I definitely want to start using it. I hope you can help me out.

Thanks!

**Comment by Loosie94** [comment]
Okay so I forgot to rename the .env file 🙃
The Fetch user authentication seems to work now, only the pages are not. 
That does seems to be an error?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13577640/194380875-e4e048b6-5c79-406d-9844-85860dc8c2d4.png">

**Comment by bryantgillespie** [comment]
Hmm it looks like there is an issue fetching the pages.

Did you adjust the permissions for the Pages collection?

**Comment by Loosie94** [comment]
I have found the issue. 
I enabled the (default) "Status" field as I saw that has been used in Content.vue. Then set my demo page on "Published", and now it's working.

Maybe its good to mention this in the readme? :)
Thanks though!

**Comment by quentinglorieux** [comment]
same problem, same fix :)

**Comment by bryantgillespie** [comment]
Sorry gents. I'll add a line about making sure to add the Optional System Fields when creating the collection to the readme.
